<?php
/**

 */
?>
<main class="container" id="accueil">
	<form id="formAuth" action="<?= getUrl('utilisateur', 'files', 'sendfile') ?>" method="post">
		<div>
			<fieldset>
				<legend>Ecole</legend>
				<div>
					<label for="identifiant"></label>
					<input type="text" id="identifiant" name="chIdentifiant">
				</div>
			</fieldset>
		</div>
		<div>

		</div>
		<div class="buttons">
			<button type="submit" class="btn-black-on-white">Envoyer</button>
		</div>
	</form>
</main>