<?php

	/**
	 * @var string $action
	 * @var string $page
	 * @var string $defaultLanguage
	 * @var string $tokenSent
	 *
	 */
?>
<main id="renew-password">
	<?php if ($action == 'ask-renew') : ?>
	<section class="section-etapes container section-etape1">
		<h4 class="phrase1">Demander le renouvellement de mon mot de passe</h4>
		<form id="formAskToken" action="" method="post">
			<p>Veuillez renseigner l'adresse email associée à votre compte.</p>
			<p>Un email vous sera transmis contenant un lien vous dirigeant vers un formulaire qui vous permettra de saisir votre nouveau mot de passe.</p>
			<p>Si vous ne recevez pas ce mail, c'est que votre adresse mail n'est pas correctement renseignée ou qu'elle n'existe pas.</p>
			<div>
				<fieldset>
					<legend><?= Traducteur::getTraduction('00036', $defaultLanguage) ?></legend>
					<div>
						<label for="mail"></label>
						<input type="email" id="mail" name="chEmail">
					</div>
				</fieldset>
			</div>
			<div class="buttons">
				<button id="btnDemandResetPassword" class="btn btn-outline" type="button"><?= Traducteur::getTraduction('00187', $defaultLanguage) ?></button>
			</div>
		</form>
	</section>
	<?php else: ?>
	<section class="section-etapes container section-etape2">
		<h4 class="phrase1">Renouveler mon mot de passe</h4>
		<?php if (!($tokenValid ?? false)): ?>
			<p>Ce lien n'est plus valide ! <br>Veuillez renouveler votre demande de réinitialisation de votre mot de passe !</p>
		<?php else: ?>
		<form id="formSetNewPassword" action="" method="post">
			<p>Veuillez saisir votre nouveau mot de passe.</p>
			<div class="passwords">
				<fieldset>
					<legend><?= Traducteur::getTraduction('00113', $defaultLanguage) ?></legend>
					<div>
						<label for="mdp"></label>
						<input type="password" id="mdp" name="chMdp">
						<a id="oeil-ouvert" class="oeil-ouvert"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye.png" alt="Oeil ouvert"></a>
						<a id="oeil-ferme" class="oeil-ferme"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye_close.png" alt="Oeil fermé"></a>
					</div>
				</fieldset>
			</div>
			<div class="passwords">
				<fieldset>
					<legend><?= Traducteur::getTraduction('00134', $defaultLanguage) ?> <?= Traducteur::getTraduction('00113', $defaultLanguage) ?></legend>
					<div>
						<label for="confirmer-mdp"></label>
						<input type="password" id="confirmer-mdp">
						<a id="oeil-ouvert-confirmer" class="oeil-ouvert"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye.png" alt="Oeil ouvert"></a>
						<a id="oeil-ferme-confirmer" class="oeil-ferme"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye_close.png" alt="Oeil fermé"></a>
					</div>
				</fieldset>
			</div>
			<div class="buttons">
				<input type="hidden" id="champToken" name="chToken" value="<?= $tokenSent ?>">
				<button id="btnSendNewPassword" class="btn btn-outline" type="button"><?= Traducteur::getTraduction('00187', $defaultLanguage) ?></button>
			</div>
		</form>
		<?php endif; ?>
	</section>
	<?php endif; ?>
</main>