<?php

	/**
	 * @var string $action
	 * @var string $page
	 * @var string $defaultLanguage
	 * @var string $tokenSent
	 *
	 */
?>
<main id="renew-password">
	<?php if ($action == 'define-new-password') : ?>
	<section class="section-etapes container section-etape2">
		<h4 class="phrase1">Créer mon mot de passe</h4>
		<?php if (!($tokenValid ?? false)): ?>
			<p>Ce lien n'est plus valide ! <br>Veuillez renouveler votre demande de réinitialisation de votre mot de passe !</p>
		<?php else: ?>
		<form id="formSetNewPassword" action="" method="post">
			<p>Veuillez saisir votre nouveau mot de passe.</p>
			<div class="passwords">
				<fieldset>
					<legend>Mot de passe</legend>
					<div>
						<label for="mdp"></label>
						<input type="password" id="mdp" name="chMdp">
						<a id="oeil-ouvert" class="oeil-ouvert"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye.png" alt="Oeil ouvert"></a>
						<a id="oeil-ferme" class="oeil-ferme"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye_close.png" alt="Oeil fermé"></a>
					</div>
				</fieldset>
			</div>
			<div class="passwords">
				<fieldset>
					<legend>Confirmez votre mot de passe</legend>
					<div>
						<label for="confirmer-mdp"></label>
						<input type="password" id="confirmer-mdp">
						<a id="oeil-ouvert-confirmer" class="oeil-ouvert"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye.png" alt="Oeil ouvert"></a>
						<a id="oeil-ferme-confirmer" class="oeil-ferme"><img class="icon--fixed-xsm" src="<?= HTML_PUBLIC_IMAGES_DIR ?>pictos/eye_close.png" alt="Oeil fermé"></a>
					</div>
				</fieldset>
			</div>
			<div class="buttons">
				<input type="hidden" id="champToken" name="chToken" value="<?= $tokenSent ?>">
				<button id="btnSendNewPassword" class="btn btn-outline" type="button">Envoyer</button>
			</div>
		</form>
		<?php endif; ?>
	</section>
	<?php endif; ?>
</main>