<?php
	/**
	 * @var array $lstEcoles
	 * @var Ecole $uneEcole
	 */
?>
<main class="container" id="formViewEvaluations">
	<h2>Envoyer un fichier</h2>
	<form id="formInfos" action="" method="post">
		<div class="field-formulaire">
			<fieldset>
				<legend>Ecole</legend>
				<div>
					<label for="champEcole"></label>
					<select id="champEcole" name="chEcole">
						<option value="0">Sélectionner votre école</option>
						<?php
							$script = '';
							foreach ($lstEcoles as $uneEcole) {
								$script .= '<option value="'.$uneEcole->getId().'">'.$uneEcole->getNom().'</option>';
							}
							print($script);
						?>
					</select>
				</div>
			</fieldset>
		</div>
		<div class="field-formulaire">
			<fieldset>
				<legend>Classe / Section</legend>
				<div>
					<label for="champClasse"></label>
					<select id="champClasse" name="chClasse">
						<option value="0">Sélectionner votre classe</option>
					</select>
				</div>
			</fieldset>
		</div>
		<div class="field-formulaire">
			<fieldset>
				<legend>Etudiant</legend>
				<div>
					<label for="champEtudiant"></label>
					<select id="champEtudiant" name="chEtudiant">
						<option value="0">Sélectionner votre nom</option>
					</select>
				</div>
			</fieldset>
		</div>
		<div class="buttons">
			<button type="button" class="btn-black-on-white" id="btnAskForCode">Demander l'acces</button>
		</div>
		<div class="field-formulaire">
			<fieldset>
				<legend>Code de connexion</legend>
				<div>
					<label for="champCodeConnexion"></label>
					<input type="text" id="champCodeConnexion" name="chCodeConnexion" maxlength="6" >
				</div>
			</fieldset>
		</div>
		<div class="field-formulaire">
			<fieldset>
				<legend>Evaluation</legend>
				<div>
					<label for="champEvaluation"></label>
					<select id="champEvaluation" name="chEvaluation">
						<option value="0">Toutes les évaluations</option>
					</select>
				</div>
			</fieldset>
		</div>
		<div class="buttons">
			<button type="button" class="btn-black-on-white" id="btnSbmitForm">Visualiser</button>
		</div>
	</form>
	<div id="tableauEvaluations" class="container hidden">
	</div>
</main>