<?php
	global $userLogged;
?>
<main class="container" id="accueil">
	<div class="buttons">
		<?php if ($userLogged->hasRole(DAORoles::getById(3)) OR !$userLogged->isAuthentified()): ?>
			<a href="<?= getUrl('evaluations', 'student', 'view') ?>" class="btn btn-black-on-white">Voir mes évaluations</a>
			<a href="<?= getUrl('evaluations', 'files', 'send') ?>" class="btn btn-black-on-white hidden">Envoyer un fichier</a>
			<a href="<?= HTML_PUBLIC_ASSETS_DIR.'GESTION_NOTES.mdb' ?>" download="" class="btn btn-black-on-white">Télécharger le fichier pour ACCESS / BDD</a>
		<?php endif; ?>

		<?php if ($userLogged->isAuthentified() AND ($userLogged->isAdmin() OR $userLogged->hasRole(DAORoles::getById(1)) OR $userLogged->hasRole(DAORoles::getById(3)))): ?>
			<a href="<?= getUrl('gestion', 'evaluations', 'view') ?>" class="btn btn-black-on-white">Voir les évaluations</a>
			<a href="<?= getUrl('gestion', 'files', 'view') ?>" class="btn btn-black-on-white">Voir les envois</a>
		<?php endif; ?>
	</div>
</main>