<!-- Script JS -->
<?php
	if (isset($includedJSScriptsFirst) and is_array($includedJSScriptsFirst) and !empty($includedJSScriptsFirst)){
		includeJsScripts($includedJSScriptsFirst);
	}
	// Inclusion de tous les scripts communs
	$includedJSCommonScripts = [HTML_PUBLIC_SCRIPTS_DIR . "common-actions.js", HTML_PUBLIC_SCRIPTS_DIR . "scripts.js", HTML_PUBLIC_SCRIPTS_DIR . "modals.js", HTML_PUBLIC_SCRIPTS_DIR . "messageBox.js"];
	includeJsScripts($includedJSCommonScripts);
?>
<?php
	if (isset($includedJSScripts) and is_array($includedJSScripts) and !empty($includedJSScripts)){
		includeJsScripts($includedJSScripts);
	}
?>
</body>

</html>