<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport"
		  content="width=device-width, initial-scale=1.0, user-scalable=yes, minimum-scale=1.0, maximum-scale=3.0">
	<meta name="application-name" content="Devatom.net">
	<meta name="apple-mobile-web-app-title" content="Devatom.net">
	<title>Votre code de connexion</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap');

		body {
			margin: 0;
			padding: 0;
			width: 100%;
		}

		html, body, * {
			font-family: "Roboto", Verdana, serif;
			box-sizing: border-box;
			font-size: max(12px, 0.9rem);


		}

		body, table, td, a {
			text-size-adjust: 100%;
			-ms-text-size-adjust: 100%;
			-webkit-text-size-adjust: 100%;
		}

		table, td {
			mso-table-rspace: 0;
			mso-table-lspace: 0;
		}

		img {
			-ms-interpolation-mode: bicubic;
		}


		table {
			border-collapse: collapse !important;
		}

		a {
			color: inherit;
			text-decoration: none;
		}

		a, a:link, a:hover, a:visited, a:active {
			text-decoration: none;
			font-size: inherit;
			color: black;
			background: transparent no-repeat;
		}

		a:hover {
			color: #fe9b04;
			box-shadow: none;
		}

		#logo {
			width: 3rem;
			height: fit-content;
			margin: 0 1rem 0 0;
		}

		#titre {
			font-size: 1.3rem;
		}

		#reseaux-follow {
			display: flex;
			height: 100%;
			flex-direction: row;
			justify-content: flex-end;
			align-items: center;
		}

		#reseaux-follow .reseaux-sociaux {
			min-height: 2.5rem;
			width: 100%;
			margin-top: 0;
			justify-content: flex-end;
			margin-bottom: 0;
			padding-left: 0;
			display: flex;
			flex-wrap: wrap;
			align-items: center;
			list-style: none;
			gap: 1rem;
		}

		#reseaux-follow .reseaux-sociaux li:first-of-type {
			display: block;
			width: 100%;
		}

		#reseaux-follow .reseaux-sociaux li a.button {
			max-width: max-content;
			background: initial;
			color: black;
			font-family: "Roboto Medium", sans-serif;
			letter-spacing: 0.1rem;
			text-align: center;
			text-transform: uppercase;
			border-radius: 0;
			padding: 3px 5px;
			border: solid black 1px;
			cursor: pointer;
			-webkit-appearance: button;
			white-space: nowrap;
			display: inline-block;
		}

		#reseaux-follow .reseaux-sociaux li a.button:hover {
			color: #fe9b04;
			box-shadow: none;
		}

		#reseaux-follow .reseaux-sociaux li a:not(.button) {
			display: block;
			width: 1.5rem;
			height: 1.5rem;
		}

		#reseaux-follow .reseaux-sociaux li a:not(.button) svg {
			width: 100%;
			height: 100%;
		}

		@media screen and (min-width: 480px) {
			#logo {
				width: 5rem;
				margin: 0 2rem 0 0
			}

			#titre {
				font-size: 2rem;
			}

			#reseaux-follow .reseaux-sociaux {
				flex-wrap: wrap;
				height: 2.5rem;
				width: 100%;
				margin-top: 0;
				justify-content: flex-end;
				margin-bottom: 0;
				padding-left: 0;
				display: flex;
				align-items: center;
				list-style: none;
				gap: 2rem;
			}

			#reseaux-follow .reseaux-sociaux li:first-of-type {
				display: initial;
				width: initial;
			}
		}

		@media screen and (min-width: 575px) {
			html, body, * {
				font-size: 1.1rem !important;
			}

			#reseaux-follow .reseaux-sociaux li a.button {
				padding: 5px 30px;
			}
		}

		@media screen and (min-width: 991px) {
			html, body, * {
				font-size: 1.2rem !important;
			}
		}
	</style>
</head>
<body style="margin: 0; padding: 0; font-family: Roboto, Verdana, serif; box-sizing: border-box; ">
<table style="border: none; width: 100%; border-collapse: collapse">
	<tr>
		<td style="padding: 10px 0 30px 0;">
			<table style="width: 90%; margin: 0 auto; border: 1px solid #cccccc; border-collapse: collapse;">
				<tr>
					<td style="background-color: #ffffff; padding: 40px 0 30px 2rem; text-align: left;">
						<img id="logo" style="display: inline-block;vertical-align: middle;" src="{{url_image_logo}}"
							 alt="Logo"/>
						<h1 id="titre"
							style="text-transform: uppercase; display: inline-block;vertical-align: middle;margin: 0;">
							<a style="text-decoration: none; color: black" href="{{url_application}}"
							   target="_blank">{{nom_application}}</a></h1>
					</td>
				</tr>
				<tr>
					<td style="background-color: #ffffff; padding: 40px 20px 40px 3rem;">
						<table style="width: 100%; border-collapse: collapse">
							<tr>
								<td style="color: #153643; font-family: Roboto, Verdana, serif; ">
									<b>Votre code de connexion</b>
								</td>
							</tr>
							<tr>
								<td style="padding: 20px 0 0 0; color: #153643; font-family: Roboto, Verdana, serif; font-size: 1rem; line-height: 20px;">
									<p>Bonjour, vous recevez cet email car vous avez demandé à recevoir votre code de connexion.</p>
									<p>Le code de connecion suivant vous a été attribué automatiquement : {{generated_code}}</p>
									<p>Ce code est valide jusqu'au {{date_validite_code}}</p>
									<p>Passé cette date, vous devrez effectuer une nouvelle demande de code de connexion.</p>
									<p>Merci de votre confiance et à très bientôt,</p>
									<p>{{nom_entreprise}}</p>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="display: block; background-color: #fe9b04; padding: 1rem;">
						<table style="width: 100%; border: none; border-collapse: collapse">
							<tr>
								<td style="color: #ffffff; font-family: Roboto, Verdana, serif; font-size: 14px; width:75%">
									<p>Vous recevez cet email automatiquement, si vous n'en êtes pas le demandeur, veuillez ne pas tenir compte de son contenu.</p>
									<p>&copy; {{annee}} {{nom_entreprise}}. Tous droits réservés.</p>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</body>
</html>